# TarsBikeCraft Homologação

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-tarsbike-homolog
  namespace: argocd
spec: 
  project: default

  source:
    repoURL: https://github.com/jpablolima/k8s.git
    targetRevision: HEAD
    path: homolog 
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-tarsbike-homolog
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true



---
# TarsBikeCraft Produção
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-nodejs
  namespace:  argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/jpablolima/k8s.git
    targetRevision: HEAD
    path: prod 
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-tarsbike-prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
  
    automated:
      selfHeal: true
      prune: true


---

# TarsBikeCraft Produção
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-nodejs
  namespace:  argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/jpablolima/k8s.git
    targetRevision: HEAD
    path: nodejs 
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-nodejs

  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
  
    automated:
      selfHeal: true
      prune: true