apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarsbikecraft-deployment-prod

spec:
  replicas: 6
  selector:
    matchLabels:
      app: tarsbike-craft-prod
  template:
    metadata:
      labels:
        app: tarsbike-craft-prod
    spec:
      containers:
        - name: tarsbike-craft-prod
          image: jpablolima/apache2tarsbikecraft:1.1.0
          ports: 
            - containerPort: 80