apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-tarsbike-prod

spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-tarsbike-prod
  template:
    metadata:
      labels:
        app: myapp-tarsbike-prod
    spec:
      containers:
        - name: myapp-tarsbike-prod
          image: jpablolima/apache2tarsbikecraft:latest
          ports: 
            - containerPort: 8081